Syed Ramish Ali <br>
Final Project <br>
Project Title : Job Search Pro <br>

<h1> Welcome To Job Search Pro</h1>
    
<h3>Use the tool to search jobs all across the US and get Jobs from any popular job search site including Indeed,Linkedin or Monster.com</h3>

<h3>Use our analysis tool to get real time salary information and future outlook for your job title and area</h3>

In [1]:
def salaryAnalysis(jobTitle):
    #import pandas as pd
    pd.options.display.html.use_mathjax = False
    
    jobTitle = jobTitle.replace(" ","-")
    url = "https://www.paysa.com/salaries/" + jobTitle + "--t"
     
    #Identify Yourself
    headers = {"user-agent": "paysaBot/1.0"}
    page = requests.get(url, headers = headers)


    if page.status_code != requests.codes.ok :
        print("Request was not successful, status code:", page.status_code)
        exit()

    #Parse using Beautiful Soup
    soup = BeautifulSoup(page.content, 'html.parser')
    #print(soup)
    
    jobs = soup.findAll('div',{'class':'salary-table'})
    entries = jobs[1].findAll('td')
    
    percentile =[]
    salary = []
    
    for i in range(len(entries)):
        en = entries[i].getText().strip()
        if (i%2 == 0):
            percentile.append(en)
        else :
            salary.append(en)
    
    df= pd.DataFrame(data = {"Percentile":percentile, "Salary":salary})
    print("salary analysis for " + jobTitle )
    return (df)

In [2]:
websites = ["linkedin","monster","indeed"]

jobTitle = input("Please Enter a Job Title:")
location = input("Please Enter location:")
print()
jobTitle2 = jobTitle

while True:
    print("Please Enter the website you want to search")
    website = input("Type indeed, Linkedin or monster: ")
    website = website.lower()
    if (website in websites):
        break
    print("Your input is incorrect")
    

print()
print("You want to search " + jobTitle + " jobs located in " + location + " using " + website +".com")

Please Enter a Job Title:software engineer
Please Enter location:boston

Please Enter the website you want to search
Type indeed, Linkedin or monster: linkedin

You want to search software engineer jobs located in boston using linkedin.com

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd


if (website == "indeed"):
    pd.options.display.html.use_mathjax = False
    
    jobTitle = jobTitle.replace(" ","+")
    url = "https://www.indeed.com/jobs?q="+ jobTitle + "\&" + "l=" + location
    
    
    #Identify Yourself
    headers = {"user-agent": "IndeedBot/1.0"}
    page = requests.get(url, headers = headers)


    if page.status_code != requests.codes.ok :
        print("Request was not successful, status code:", page.status_code)
        exit()

    #Parse using Beautiful Soup
    soup = BeautifulSoup(page.content, 'html.parser')

    #Create a list of all jobs
    jobs = soup.find_all('div',{'class':'jobsearch-SerpJobCard'})

    #Declare lists
    title = []
    company = []
    location = []
    links = []
    

    #Go through all the jobs and save the necessary information in the lists
    for j in jobs:
        t = j.find('h2',{'class':'title'})
        t = t.get_text().strip()
        title.append(t)
        
        jobLink = j.find('a')
        link = "https://www.indeed.com" + jobLink.get('href')     
        links.append(link)

        c = j.find('span',{'class':'company'})
        c = c.get_text().strip()
        company.append(c)

        #location is either stored in a span tag or div tag therefore go through both
        l = j.find('span',{'class':'location'})
        try:
            l = l.get_text().strip()
        except AttributeError:
            l = j.find('div',{'class':'location'})
            l = l.get_text().strip()
        location.append(l)

In [4]:
if (website == "linkedin"):
    pd.options.display.html.use_mathjax = False
    
    jobTitle = jobTitle.replace(" ","-")
    
    url = "https://www.linkedin.com/jobs/"+ jobTitle + "-jobs-" + location
    
    #Identify Yourself
    headers = {"user-agent": "LinkedinBot/1.0"}
    page = requests.get(url, headers = headers)


    if page.status_code != requests.codes.ok :
        print("Request was not successful, status code:", page.status_code)
        exit()

    #Parse using Beautiful Soup
    soup = BeautifulSoup(page.content, 'html.parser')
    
    #Create lists
    title = []
    company = []
    location = []
    links = []
    
    #Both the title of the job and the link to the job page are in the same <a> tag.
    jobTitle = soup.find_all('a',{'class':'result-card__full-card-link'})
    for job in jobTitle:
        link = job.get('href')   
        t = job.get_text().strip()
        title.append(t)
        links.append(link)
        
    employerList = soup.find_all('a',{'class':'result-card__subtitle-link job-result-card__subtitle-link'})
    for employer in employerList:
        e = employer.get_text().strip()
        company.append(e)
        
    locationList = soup.find_all('span',{'class':'job-result-card__location'})
    for l in locationList:
        l = l.get_text().strip()
        location.append(l)

In [5]:
if (website == "monster"):
    pd.options.display.html.use_mathjax = False
    
    jobTitle = jobTitle.replace(" ","-")
    
    url = "https://www.monster.com/jobs/search/?q="+ jobTitle + "&where=" + location
          
    
    #Identify Yourself
    headers = {"user-agent": "monsterBot/1.0"}
    page = requests.get(url, headers = headers)


    if page.status_code != requests.codes.ok :
        print("Request was not successful, status code:", page.status_code)
        exit()

    #Parse using Beautiful Soup
    soup = BeautifulSoup(page.content, 'html.parser')
    
    #Create lists
    title = []
    company = []
    location = []
    links = []
    
    #Create a list of all jobs
    jobs = soup.find_all('div',{'class':'summary'})
    
    for j in jobs:
        t = j.find('h2',{'class':'title'})
        t = t.get_text().strip()
        title.append(t)
    
        c = j.find('div',{'class':'company'})
        c = c.get_text().strip()
        company.append(c)
        
        l = j.find('div',{'class':'location'})
        l = l.get_text().strip()
        location.append(l)
        
        link = j.find('a')
        link = link.get('href')   
        links.append(link)

In [6]:
df= pd.DataFrame(data = {"Job Title":title, "Company Name":company, "Location":location, "Link":links})
df

,Job Title,Company Name,Location,Link
0,Application Developer,IBM,Greater Boston,https://www.linkedin.com/jobs/view/application...
1,Software Developer,Verisk,"Lexington, MA",https://www.linkedin.com/jobs/view/software-de...
2,Full Stack Software Engineer,Chewy,Greater Boston,https://www.linkedin.com/jobs/view/full-stack-...
3,Software Engineer,McKinsey & Company,"Waltham, MA",https://www.linkedin.com/jobs/view/software-en...
4,Solution Engineer (All Levels),Salesforce,Greater Boston,https://www.linkedin.com/jobs/view/solution-en...
5,Software Engineer - Entry Level,PathAI,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
6,Application Developer,Trillium Staffing Solutions,Greater Boston,https://www.linkedin.com/jobs/view/application...
7,Software Engineer,Fidelity Investments,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
8,Software Engineer (Backend),WHOOP,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
9,Software Engineer,Huxley,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
10,Software Engineer,Projectus Consulting,"Boston, MA",https://www.linkedin.com/jobs/view/software-en...
11,Software Engineer,Citrix,"Burlington, MA",https://www.linkedin.com/jobs/view/software-en...
12,Software Engineer (All Levels),Algorand,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
13,Web Developer,IT Trailblazers,Greater Boston,https://www.linkedin.com/jobs/view/web-develop...
14,Software Engineer,Nasuni,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
15,Web Developer,Triniti Corporation,"Cambridge, MA",https://www.linkedin.com/jobs/view/web-develop...
16,Web Developer,Epic,Greater Boston,https://www.linkedin.com/jobs/view/web-develop...
17,Software Engineer,Vivid Resourcing Ltd,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
18,Software Engineer,Alexander Technology Group,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
19,"Software Engineer, Risk",Venmo,"Newton Centre, MA",https://www.linkedin.com/jobs/view/software-en...
20,Software Engineer,Vizgen,"Cambridge, MA",https://www.linkedin.com/jobs/view/software-en...
21,Software Engineer,Alteryx,Greater Boston,https://www.linkedin.com/jobs/view/software-en...
22,Software Engineer,HubSpot,"Cambridge, MA",https://www.linkedin.com/jobs/view/software-en...
23,Full Stack Software Developer,Veson Nautical,Greater Boston,https://www.linkedin.com/jobs/view/full-stack-...
24,Java Developer,Motion Recruitment,"Boston, MA",https://www.linkedin.com/jobs/view/java-develo...

In [7]:
salaryAnalysis(jobTitle2)

salary analysis for software-engineer

  Percentile       Salary
0        10%   $82,397.44
1        25%   $93,321.30
2     median  $107,165.06
3        75%  $123,062.47
4        90%  $139,377.51

In [8]:
salaryAnalysis("general surgeon")

salary analysis for general-surgeon

  Percentile       Salary
0        10%   $93,271.50
1        25%  $133,367.61
2     median  $198,427.31
3        75%  $295,224.58
4        90%  $422,137.50

In [9]:
salaryAnalysis("teacher")

salary analysis for teacher

  Percentile      Salary
0        10%  $36,899.98
1        25%  $41,934.36
2     median  $48,337.42
3        75%  $55,718.16
4        90%  $63,319.98